#!/usr/bin/python
import npyscreen,subprocess,json,urllib,os,sys

def consul(query):    
    consul_host = os.getenv('CONSUL_HOST', "127.0.0.1")
    return json.loads(urllib.urlopen("http://%(consul_host)s:8500/v1/%(query)s" % locals()).read())

def matches(server):
    if len(sys.argv) > 1:
        return (sys.argv[1] in server)
    return True

def ops(i):
    if len(sys.argv) > 2:
        return "/usr/bin/sudo /usr/bin/docker-enter %s %s" % (i,sys.argv[2])
    else:
        return "/usr/bin/sudo /usr/bin/docker-enter %s" % i

class ContainerTree(npyscreen.MLTree):
    def h_select(self,ch):
       item = self.values[self.cursor_line]       
       global execl
       ssh_opts = [i for i in os.getenv('SSH_OPTS', "").split(" ") if len(i)>0]
       if item.operation:
          execl = ["/usr/bin/ssh","-t","-A","-o","StrictHostKeyChecking=no"]+ssh_opts+[ item.address, item.operation]
       else:
          execl = ["/usr/bin/ssh","-t","-A","-o","StrictHostKeyChecking=no"]+ssh_opts+[ item.address]
       self.parentForm.parentApp.switchForm(None)

class BaseTreeForm(npyscreen.FormBaseNew):
      def create(self):
        env = consul("agent/self")["Config"]["Datacenter"]
        title = "In the "+env+" dc:"
        cats = [consul("catalog/service/"+k) for (k,v) in consul("catalog/services").items() if 'registrator' in v]
        ssh  = consul("catalog/service/ssh")
        addresses = dict([(host['Node'],host['Address']) for host in ssh])
        hosts = dict([(host['Node'],[]) for host in ssh if matches(host['Node'])])
        #title = ssh[0]
        dockers = [serv['ServiceID'].split(":")[0:2]+[serv["ServiceName"]] for serv in sum(cats,[])]
        types=dict()
        for (k,v,t) in dockers:
            if k in hosts:
                hosts[k].append(v)
                types[v]=t
        treedata = npyscreen.NPSTreeData(content=title, selectable=True, selected=True, ignoreRoot=False)
        for k,v in hosts.items():
            branch = treedata.newChild(content=k, selectable=True)
            branch.operation = False
            branch.address = addresses[k]
            for i in v:
                leaf = branch.newChild(content=types[i], selectable=True)
                leaf.operation = ops(i)
                leaf.address = addresses[k]
        wgtree = self.add(ContainerTree)
        wgtree.parentForm = self
        wgtree.values = treedata
      

class ContainerTreeApp(npyscreen.NPSAppManaged):
    def onStart(self):
        self.addForm("MAIN", BaseTreeForm, framed=False, max_height=15)

    def onCleanExit(self):
        pass
   
    def change_form(self, name):
        self.switchForm(name)


def main():
   try:
       if len(consul("catalog/service/ssh")) < 1:
           print "No ssh service in consul, try the included ssh.json"
   except IOError:
       consul_host = os.getenv('CONSUL_HOST', "127.0.0.1")
       print "Error connecting to consul (%(consul_host)s:8500)" % locals()
   else:
       TA = ContainerTreeApp()
       TA.run()
       if len(execl) > 0:
           print " ".join(execl)
           subprocess.call(execl)

if __name__ == '__main__':
    main()
